# embed_spv.cmake
if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VAR_NAME)
  message(FATAL_ERROR "Usage: cmake -P embed_spv.cmake -DINPUT=... -DOUTPUT=... -DVAR_NAME=...")
endif()
file(READ "${INPUT}" HEX)
string(LENGTH "${HEX}" HEXLEN)
math(EXPR BYTES "${HEXLEN} / 2")
set(OUT "// Generated from ${INPUT}\nconst unsigned int ${VAR_NAME}_size = ${BYTES};\nconst unsigned char ${VAR_NAME}[] = {\n")
set(i 0)
while(i LESS HEXLEN)
  string(SUBSTRING "${HEX}" ${i} 2 byte)
  string(TOUPPER "${byte}" BYTE)
  set(OUT "${OUT} 0x${BYTE},")
  math(EXPR i "${i} + 2")
endwhile()
set(OUT "${OUT}\n};\n")
file(WRITE "${OUTPUT}" "${OUT}")
message(STATUS "Wrote embedded SPV to ${OUTPUT}")
